using System;
using System.Collections.Generic;

using Microsoft.Xna.Framework;

using Terraria;
using Terraria.ID;
using Terraria.ModLoader;
using Terraria.Graphics.Effects;
using Terraria.Graphics.Shaders;


namespace MechParadise
{
    public class MechParadise : Mod
    {
        public MechParadise()
        {
            Properties = new ModProperties()
            {
                Autoload = true
            };
        }
    }

    public class Recipes
    {
        public void AddRecipes(Mod mod)
        {
            ModRecipe recipe;

            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.StoneBlock, 30);
            recipe.AddIngredient(ItemID.Wire, 1);
            recipe.AddIngredient(ItemID.ThrowingKnife, 50);
            recipe.AddTile(TileID.TinkerersWorkbench);
            recipe.SetResult(ItemID.DartTrap, 1);
            recipe.AddRecipe();

            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.CopperBar, 5);
            recipe.AddIngredient(ItemID.Gel, 50);
            recipe.AddTile(TileID.TinkerersWorkbench);
            recipe.SetResult(ItemID.Wire, 10);
            recipe.AddRecipe();

            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.TinBar, 5);
            recipe.AddIngredient(ItemID.Gel, 50);
            recipe.AddTile(TileID.TinkerersWorkbench);
            recipe.SetResult(ItemID.Wire, 10);
            recipe.AddRecipe();

            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.DartTrap, 1);
            recipe.AddIngredient(ItemID.LihzahrdBrick, 20);
            recipe.AddIngredient(ItemID.VialofVenom, 1);
            recipe.AddTile(TileID.TinkerersWorkbench);
            recipe.SetResult(ItemID.SuperDartTrap, 1);
            recipe.AddRecipe();

            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.DartTrap, 1);
            recipe.AddIngredient(ItemID.LihzahrdBrick, 20);
            recipe.AddIngredient(ItemID.Gel, 200);
            recipe.AddTile(TileID.TinkerersWorkbench);
            recipe.SetResult(ItemID.FlameTrap, 1);
            recipe.AddRecipe();

            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.Wire, 1);
            recipe.AddIngredient(ItemID.LihzahrdBrick, 30);
            recipe.AddIngredient(ItemID.SpikyBall, 200);
            recipe.AddTile(TileID.TinkerersWorkbench);
            recipe.SetResult(ItemID.SpikyBallTrap, 1);
            recipe.AddRecipe();

            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.Wire, 1);
            recipe.AddIngredient(ItemID.LihzahrdBrick, 30);
            recipe.AddIngredient(ItemID.Spike, 1);
            recipe.AddIngredient(ItemID.IronBar, 5);
            recipe.AddTile(TileID.TinkerersWorkbench);
            recipe.SetResult(ItemID.SpearTrap, 1);
            recipe.AddRecipe();

            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.Wire, 1);
            recipe.AddIngredient(ItemID.LihzahrdBrick, 30);
            recipe.AddIngredient(ItemID.Spike, 1);
            recipe.AddIngredient(ItemID.LeadBar, 5);
            recipe.AddTile(TileID.TinkerersWorkbench);
            recipe.SetResult(ItemID.SpearTrap, 1);
            recipe.AddRecipe();
        
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.StoneBlock, 50);
            recipe.AddIngredient(ItemID.Wire, 1);
            recipe.AddIngredient(ItemID.GreaterHealingPotion, 10);
            recipe.AddTile(TileID.HeavyWorkBench);
            recipe.SetResult(ItemID.HeartStatue, 1);
            recipe.AddRecipe();
        
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.StoneBlock, 50);
            recipe.AddIngredient(ItemID.Wire, 1);
            recipe.AddIngredient(ItemID.GreaterManaPotion, 10);
            recipe.AddTile(TileID.HeavyWorkBench);
            recipe.SetResult(ItemID.StarStatue, 1);
            recipe.AddRecipe();
        
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.StoneBlock, 100);
            recipe.AddIngredient(ItemID.Wire, 1);
            recipe.AddTile(TileID.HeavyWorkBench);
            recipe.SetResult(ItemID.BloodZombieStatue, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.StoneBlock, 100);
            recipe.AddIngredient(ItemID.Wire, 1);
            recipe.AddTile(TileID.HeavyWorkBench);
            recipe.SetResult(ItemID.DripplerStatue, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.StoneBlock, 100);
            recipe.AddIngredient(ItemID.Wire, 1);
            recipe.AddTile(TileID.HeavyWorkBench);
            recipe.SetResult(ItemID.HopliteStatue, 1);
            recipe.AddRecipe();
            //recipe = new ModRecipe (mod);
            //recipe.AddIngredient(ItemID.StoneBlock, 100);
            //recipe.AddIngredient(ItemID.Wire, 1);
            //recipe.AddTile(TileID.HeavyWorkBench);
            //recipe.SetResult(ItemID.VikingStatue, 1);
            //recipe.AddRecipe(); Can't remember what the Viking statue is called
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.StoneBlock, 100);
            recipe.AddIngredient(ItemID.Wire, 1);
            recipe.AddTile(TileID.HeavyWorkBench);
            recipe.SetResult(ItemID.HarpyStatue, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.StoneBlock, 100);
            recipe.AddIngredient(ItemID.Wire, 1);
            recipe.AddIngredient(ItemID.UnicornHorn, 3);
            recipe.AddTile(TileID.HeavyWorkBench);
            recipe.SetResult(ItemID.UnicornStatue, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.StoneBlock, 100);
            recipe.AddIngredient(ItemID.Wire, 1);
            recipe.AddIngredient(ItemID.LightKey, 1);
            recipe.AddIngredient(ItemID.NightKey, 1);
            recipe.AddTile(TileID.HeavyWorkBench);
            recipe.SetResult(ItemID.ChestStatue, 1);
            recipe.AddRecipe();
        
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.BandofRegeneration, 1);
            recipe.AddIngredient(ItemID.ManaCrystal, 1);
            recipe.AddTile(TileID.TinkerersWorkbench);
            recipe.SetResult(ItemID.BandofStarpower, 1);
            recipe.AddRecipe();
    
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.Actuator, 15);
            recipe.AddIngredient(ItemID.Wire, 5);
            recipe.AddIngredient(ItemID.MechanicalLens, 1);
            recipe.AddTile(TileID.TinkerersWorkbench);
            recipe.SetResult(ItemID.ActuationAccessory, 1);
            recipe.AddRecipe();
    
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.BandofRegeneration, 1);
            recipe.AddIngredient(ItemID.LifeCrystal, 1);
            recipe.AddTile(TileID.TinkerersWorkbench);
            recipe.SetResult(ItemID.PanicNecklace, 1);
            recipe.AddRecipe();
    
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.BottledHoney, 10);
            recipe.AddIngredient(ItemID.BeeWax, 3);
            recipe.AddTile(TileID.TinkerersWorkbench);
            recipe.SetResult(ItemID.HoneyComb, 1);
            recipe.AddRecipe();
    
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(ItemID.SoulofLight, 200);
            recipe.AddIngredient(ItemID.CrystalShard, 99);
            recipe.AddIngredient(ItemID.SoulofSight, 20);
            recipe.AddTile(TileID.MythrilAnvil);
            recipe.SetResult(ItemID.RodofDiscord, 1);
            recipe.AddRecipe();
    
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.WarriorEmblem, 1);
            recipe.SetResult(ItemID.RangerEmblem, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.WarriorEmblem, 1);
            recipe.SetResult(ItemID.SorcererEmblem, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.WarriorEmblem, 1);
            recipe.SetResult(ItemID.SummonerEmblem, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.RangerEmblem, 1);
            recipe.SetResult(ItemID.WarriorEmblem, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.RangerEmblem, 1);
            recipe.SetResult(ItemID.SorcererEmblem, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.RangerEmblem, 1);
            recipe.SetResult(ItemID.SummonerEmblem, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.SorcererEmblem, 1);
            recipe.SetResult(ItemID.WarriorEmblem, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.SorcererEmblem, 1);
            recipe.SetResult(ItemID.RangerEmblem, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.SorcererEmblem, 1);
            recipe.SetResult(ItemID.SummonerEmblem, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.SummonerEmblem, 1);
            recipe.SetResult(ItemID.WarriorEmblem, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.SummonerEmblem, 1);
            recipe.SetResult(ItemID.RangerEmblem, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.SummonerEmblem, 1);
            recipe.SetResult(ItemID.SorcererEmblem, 1);
            recipe.AddRecipe();
    
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.StoneBlock, 500);
            recipe.AddIngredient(ItemID.Daybloom, 40);
            recipe.AddIngredient(ItemID.SoulofLight, 30);
            recipe.AddTile(TileID.LihzahrdFurnace);
            recipe.SetResult(ItemID.SunStone, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.StoneBlock, 500);
            recipe.AddIngredient(ItemID.Moonglow, 40);
            recipe.AddIngredient(ItemID.SoulofNight, 30);
            recipe.AddTile(TileID.LihzahrdFurnace);
            recipe.SetResult(ItemID.MoonStone, 1);
            recipe.AddRecipe();
    
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.HeartreachPotion, 5);
            recipe.AddIngredient(ItemID.LuckyHorseshoe, 1);
            recipe.AddIngredient(ItemID.ManaCrystal, 2);
            recipe.AddTile(TileID.TinkerersWorkbench);
            recipe.SetResult(ItemID.CelestialMagnet, 1);
            recipe.AddRecipe();
  
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.PixieDust, 50);
            recipe.AddIngredient(ItemID.UnicornHorn, 5);
            recipe.AddTile(TileID.MythrilAnvil);
            recipe.SetResult(ItemID.SoulofLight, 10);
            recipe.AddRecipe();
    
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.RottenChunk, 50);
            recipe.AddIngredient(ItemID.CursedFlame, 5);
            recipe.AddTile(TileID.MythrilAnvil);
            recipe.SetResult(ItemID.SoulofNight, 10);
            recipe.AddRecipe();
    
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.Vertebrae, 50);
            recipe.AddIngredient(ItemID.Ichor, 5);
            recipe.AddTile(TileID.MythrilAnvil);
            recipe.SetResult(ItemID.SoulofNight, 10);
            recipe.AddRecipe();
  
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.PrincessFish, 20);
            recipe.AddIngredient(ItemID.CrystalShard, 15);
            recipe.AddIngredient(ItemID.SoulofLight, 10);
            recipe.AddTile(TileID.MythrilAnvil);
            recipe.SetResult(ItemID.CrystalSerpent, 1);
            recipe.AddRecipe();
            
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.Ebonkoi, 20);
            recipe.AddIngredient(ItemID.SpiderFang, 15);
            recipe.AddIngredient(ItemID.SoulofNight, 10);
            recipe.AddTile(TileID.MythrilAnvil);
            recipe.SetResult(ItemID.Toxikarp, 1);
            recipe.AddRecipe();
            
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.Hemopiranha, 20);
            recipe.AddIngredient(ItemID.Ichor, 15);
            recipe.AddIngredient(ItemID.SoulofNight, 10);
            recipe.AddTile(TileID.MythrilAnvil);
            recipe.SetResult(ItemID.Bladetongue, 1);
            
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.FetidBaghnakhs, 1);
            recipe.AddTile(TileID.MythrilAnvil);
            recipe.SetResult(ItemID.ChainGuillotines, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.ChainGuillotines, 1);
            recipe.AddTile(TileID.MythrilAnvil);
            recipe.SetResult(ItemID.FetidBaghnakhs, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.ClingerStaff, 1);
            recipe.AddTile(TileID.MythrilAnvil);
            recipe.SetResult(ItemID.SoulDrain, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.SoulDrain, 1);
            recipe.AddTile(TileID.MythrilAnvil);
            recipe.SetResult(ItemID.ClingerStaff, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.DartRifle, 1);
            recipe.AddTile(TileID.MythrilAnvil);
            recipe.SetResult(ItemID.DartPistol, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.DartPistol, 1);
            recipe.AddTile(TileID.MythrilAnvil);
            recipe.SetResult(ItemID.DartRifle, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.PutridScent, 1);
            recipe.AddTile(TileID.MythrilAnvil);
            recipe.SetResult(ItemID.FleshKnuckles, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(ItemID.FleshKnuckles, 1);
            recipe.AddTile(TileID.MythrilAnvil);
            recipe.SetResult(ItemID.PutridScent, 1);
            recipe.AddRecipe();            
        }            
    }
    
    public class BossForgeRecipes
    {
        public void AddRecipes(Mod mod)
        {
            ModRecipe recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "Shadowflame", 30);
            recipe.AddIngredient(ItemID.Silk, 10);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.ShadowFlameHexDoll, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "Shadowflame", 30);
            recipe.AddIngredient(ItemID.ThrowingKnife, 50);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.ShadowFlameKnife, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "Shadowflame", 30);
            recipe.AddIngredient(ItemID.MoltenFury, 1);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.ShadowFlameBow, 1);
            recipe.AddRecipe();
            
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "FoolsGold", 25);
            recipe.AddIngredient(ItemID.ObsidianSkull, 1);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.PirateStaff, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "FoolsGold", 150);
            recipe.AddIngredient(ItemID.LuckyHorseshoe, 1);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.LuckyCoin, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "FoolsGold", 20);
            recipe.AddIngredient(ItemID.DiamondRing, 1);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.GoldRing, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "FoolsGold", 50);
            recipe.AddIngredient(ItemID.Wood, 10);
            recipe.AddIngredient(ItemID.SoulofSight, 5);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.DiscountCard);
            recipe.AddRecipe();
            
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "MartianCore", 1);
            recipe.AddIngredient(ItemID.Drax, 1);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.LaserDrill, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "MartianCore", 1);
            recipe.AddIngredient(ItemID.BrokenHeroSword, 1);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.InfluxWaver);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "MartianCore", 1);
            recipe.AddIngredient(ItemID.Bubble, 20);
            recipe.AddIngredient(ItemID.SoulofMight, 5);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.Xenopopper, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "MartianCore", 1);
            recipe.AddIngredient(ItemID.Glass, 20);
            recipe.AddIngredient(ItemID.IllegalGunParts, 1);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.LaserMachinegun, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "MartianCore", 1);
            recipe.AddIngredient(ItemID.Glass, 20);
            recipe.AddIngredient(ItemID.Ectoplasm, 5);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.ChargedBlasterCannon, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "MartianCore", 1);
            recipe.AddIngredient(ItemID.FallenStar, 10);
            recipe.AddIngredient(ItemID.MeteoriteBar, 15);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.XenoStaff, 1);
            recipe.AddRecipe();
            
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(ItemID.BeeWax, 5);
            recipe.AddIngredient(ItemID.BottledHoney, 5);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.BeeKeeper, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(ItemID.BeeWax, 5);
            recipe.AddIngredient(ItemID.BottledHoney, 5);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.BeeGun, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(ItemID.BeeWax, 5);
            recipe.AddIngredient(ItemID.BottledHoney, 5);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.BeesKnees, 1);
            recipe.AddRecipe();
            
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "UnhallowedShard", 10);
            recipe.AddIngredient(ItemID.SpaceGun, 1);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.LaserRifle, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "UnhallowedShard", 10);
            recipe.AddIngredient(ItemID.SoulofNight, 3);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.BreakerBlade, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "UnhallowedShard", 10);
            recipe.AddIngredient(ItemID.Musket, 1);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.ClockworkAssaultRifle);
            recipe.AddRecipe();
            
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "TruffleScale", 3);
            recipe.AddIngredient(ItemID.Bubble, 50);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.BubbleGun, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "TruffleScale", 3);
            recipe.AddIngredient(ItemID.MagnetSphere, 1);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.RazorbladeTyphoon, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "TruffleScale", 3);
            recipe.AddIngredient(ItemID.Chain, 5);
            recipe.AddIngredient(ItemID.Bubble, 5);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.Flairon, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "TruffleScale", 3);
            recipe.AddIngredient(ItemID.ShroomiteBar, 5);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.Tsunami, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "TruffleScale", 3);
            recipe.AddIngredient(ItemID.SharkFin, 10);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.TempestStaff);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "TruffleScale", 6);
            recipe.AddIngredient(ItemID.SoulofFlight, 20);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.FishronWings);
            recipe.AddRecipe();
            
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(null, "LunarHeart", 1);
            recipe.AddIngredient(ItemID.LunarBar, 10);
            recipe.AddIngredient(ItemID.SharkFin, 5);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.SDMG, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(null, "LunarHeart", 1);
            recipe.AddIngredient(ItemID.LunarBar, 10);
            recipe.AddIngredient(ItemID.CrystalShard, 50);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.RainbowCrystalStaff, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(null, "LunarHeart", 1);
            recipe.AddIngredient(ItemID.LunarBar, 10);
            recipe.AddIngredient(ItemID.WoodYoyo, 1);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.Terrarian, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(null, "LunarHeart", 1);
            recipe.AddIngredient(ItemID.LunarBar, 10);
            recipe.AddIngredient(ItemID.Starfury, 1);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.StarWrath, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(null, "LunarHeart", 1);
            recipe.AddIngredient(ItemID.LunarBar, 10);
            recipe.AddIngredient(ItemID.UnicornHorn, 5);
            recipe.AddIngredient(ItemID.PixieDust, 25);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.Meowmere, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(null, "LunarHeart", 1);
            recipe.AddIngredient(ItemID.LunarBar, 10);
            recipe.AddIngredient(ItemID.RocketIII, 20);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.FireworksLauncher, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(null, "LunarHeart", 1);
            recipe.AddIngredient(ItemID.LunarBar, 10);
            recipe.AddIngredient(ItemID.SoulofNight, 15);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.MoonlordTurretStaff, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(null, "LunarHeart", 1);
            recipe.AddIngredient(ItemID.LunarBar, 10);
            recipe.AddIngredient(ItemID.Book, 1);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.LunarFlareBook, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe (mod);
            recipe.AddIngredient(null, "LunarHeart", 1);
            recipe.AddIngredient(ItemID.LunarBar, 10);
            recipe.AddIngredient(ItemID.SoulofLight, 15);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.LastPrism, 1);
            recipe.AddRecipe();
            
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "HeavyPetal", 5);
            recipe.AddIngredient(ItemID.BeeGun, 1);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.WaspGun, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "HeavyPetal", 5);
            recipe.AddIngredient(ItemID.BladeofGrass, 1);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.Seedler, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "HeavyPetal", 5);
            recipe.AddIngredient(ItemID.Vilethorn, 1);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.NettleBurst, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "HeavyPetal", 5);
            recipe.AddIngredient(ItemID.CrimsonRod, 1);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.NettleBurst, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "HeavyPetal", 5);
            recipe.AddIngredient(ItemID.PirateStaff, 1);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.PygmyStaff, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "HeavyPetal", 5);
            recipe.AddIngredient(ItemID.BlueMoon, 1);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.FlowerPow, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "HeavyPetal", 5);
            recipe.AddIngredient(ItemID.RichMahogany, 40);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.LeafBlower, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "HeavyPetal", 5);
            recipe.AddIngredient(ItemID.ChlorophyteBar, 10);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.VenusMagnum, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "HeavyPetal", 5);
            recipe.AddIngredient(ItemID.Grenade, 30);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.GrenadeLauncher, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "HeavyPetal", 25);
            recipe.AddIngredient(ItemID.MeteorHamaxe, 1);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.TheAxe, 1);
            recipe.AddRecipe();
            
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(ItemID.SpookyWood, 40);
            recipe.AddIngredient(ItemID.BatWings, 1);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.BatScepter, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(ItemID.SpookyWood, 40);
            recipe.AddIngredient(ItemID.Pumpkin, 15);
            recipe.AddIngredient(ItemID.BrokenHeroSword, 1);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.TheHorsemansBlade, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(ItemID.SpookyWood, 40);
            recipe.AddIngredient(ItemID.Pumpkin, 15);
            recipe.AddIngredient(ItemID.RocketI, 5);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.JackOLanternLauncher, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(ItemID.SpookyWood, 40);
            recipe.AddIngredient(ItemID.VilePowder, 10);
            recipe.AddIngredient(ItemID.Ectoplasm, 4);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.NecromanticScroll, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(ItemID.SpookyWood, 40);
            recipe.AddIngredient(ItemID.ViciousPowder, 10);
            recipe.AddIngredient(ItemID.Ectoplasm, 4);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.NecromanticScroll, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(ItemID.SpookyWood, 40);
            recipe.AddIngredient(ItemID.IllegalGunParts, 1);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.CandyCornRifle, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(ItemID.SpookyWood, 40);
            recipe.AddIngredient(ItemID.Feather, 15);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.RavenStaff, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(ItemID.SpookyWood, 40);
            recipe.AddIngredient(ItemID.SoulofNight, 10);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.StakeLauncher, 1);
            recipe.AddRecipe();
            
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "TornWrap", 5);
            recipe.AddIngredient(ItemID.IllegalGunParts, 1);
            recipe.AddIngredient(ItemID.SoulofFright, 10);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.EldMelter, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "TornWrap", 5);
            recipe.AddIngredient(ItemID.Wood, 150);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.ChristmasTreeSword, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "TornWrap", 5);
            recipe.AddIngredient(ItemID.Wood, 100);
            recipe.AddIngredient(ItemID.FallenStar, 5);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.Razorpine, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "TornWrap", 5);
            recipe.AddIngredient(ItemID.HallowedBar, 15);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.NorthPole, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "TornWrap", 5);
            recipe.AddIngredient(ItemID.Chain, 15);
            recipe.AddIngredient(ItemID.SoulofMight, 10);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.ChainGun, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "TornWrap", 5);
            recipe.AddIngredient(ItemID.SoulofSight, 10);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.BlizzardStaff, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "TornWrap", 5);
            recipe.AddIngredient(ItemID.RocketIII, 15);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.SnowmanCannon, 1);
            recipe.AddRecipe();
            
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(ItemID.Bone, 30);
            recipe.AddIngredient(ItemID.WaterBolt, 1);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.BookofSkulls, 1);
            recipe.AddRecipe();
            
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "CoreShard", 5);
            recipe.AddIngredient(ItemID.Boulder, 15);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.StaffofEarth, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "CoreShard", 5);
            recipe.AddIngredient(ItemID.ExplosivePowder, 15);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.Stynger, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "CoreShard", 5);
            recipe.AddIngredient(ItemID.HellstoneBar, 5);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.HeatRay, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "CoreShard", 5);
            recipe.AddIngredient(ItemID.SoulofSight, 10);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.EyeoftheGolem, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "CoreShard", 5);
            recipe.AddIngredient(ItemID.Chain, 3);
            recipe.AddIngredient(ItemID.LihzahrdBrick, 20);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.GolemFist, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "CoreShard", 5);
            recipe.AddIngredient(ItemID.PickaxeAxe, 1);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.Picksaw, 1);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "CoreShard", 5);
            recipe.AddIngredient(ItemID.SoulofMight, 10);
            recipe.AddIngredient(ItemID.Ectoplasm, 4);
            recipe.AddTile(null, "BossForge");
            recipe.SetResult(ItemID.PossessedHatchet, 1);
            recipe.AddRecipe();
            }
    }        
}

